# Site settings
title: Booksprung
email: chris@booksprung.com
description: "a notebook about digital publishing"
baseurl: "/booksprung"
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
