# Site settings
title: Booksprung
email: chris@booksprung.com
description: "a notebook about digital publishing"
baseurl: "/booksprung"
url: "http://christopherwalters.github.io/booksprung"

# Build settings
markdown: kramdown
permalink: pretty
