# Site settings
title: Booksprung
email: chris@booksprung.com
description: "a notebook about digital publishing"
baseurl: "/booksprung"
url: "http://christopherwalters.github.io/booksprung"
excerpt_separator: "<!-- more -->"

# Build settings
markdown: kramdown
permalink: pretty

# Default YAML settings
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
  -
    scope:
      path: "posts"
      type: "post"
    values:
      layout: "post" # overrides previous default layout
      author: "Chris Walters"